### ISSUE TITLE
Weekly Scrum - Tuesday, March 8, 2022

### ISSUE THREAD

**Issue by Calacorm** [NicolasDuciaume/SYSC4806_Web_App#13]
Record of Scrum Meeting:

What we Did:
Tyler:
- Pushed User and Login Classes

What we are doing next:
Tyler:
- Pushing in the CI configuration and verification the pipeline works #2 

Blockers:
Tyler:
- No blockers

**Comment by NicolasDuciaume** [comment]
- Testing persistence of data through login in and login out
- Testing populating database through registration

**Comment by aimansharif** [comment]
* Worked on the UserController and UserRepository classes
* Pushed the user controller class and the user repository class

* Testing to make sure that the calls work for adding users getting all addressbook users 
* Add Heroku deployment for the project

* No Blockers
