### ISSUE TITLE
User Portal

### ISSUE THREAD

**Issue by Calacorm** [NicolasDuciaume/SYSC4806_Web_App#24]
Normal users goto this page
- See #22 for specific things paid vs unpaid can do on this page.

**Comment by nazifatanzim** [comment]
A single page that will allow a user to press a button to conduct rest calls
Add the following buttons and features:

- logout button (bring you back to login page)
- delete account button (lead to delete account page)
- rest call button
- check user status (paid vs unpaid) -> if paid, no limit; if unpaid, compare number of rest calls to limit (disable button after limit is reached)
- update db every time the rest call button is pressed (increment button press count)
