### ISSUE TITLE
March 13 Sunday Sprint Review and Sprint 2 Kickoff

### ISSUE THREAD

**Issue by Calacorm** [NicolasDuciaume/SYSC4806_Web_App#27]
What we did:
Sprint 1 - Issues
- Assign work by feature and not components
- Focus on the process, Pull CR's required with 2 reviews, tests must be included in the PR for that feature

Sprint 1 - Good stuff 
- The code works as we designed it
- The full pipeline works: Dev-Pc -> Github -> Circle -> Heroku

Sprint 2 TODO
- WHO -Assign members to features
- WHAT - flesh out the feature specs
- WHEN - Do any features depend on another?

**Comment by NicolasDuciaume** [comment]
What I did:

- Assigned users to their respective feature
- Created a Sub-feature label to link feature based issues to the main feature
- Created Sub-Feature issues which need to be done for my feature

What needs to be done:
-Complete the issues which have been added today
-Create issues for Tests for my feature
-Create respective branches for all of my sub-features
