### ISSUE TITLE
Weekly Scrum - Tuesday, March 1, 2022

### ISSUE THREAD

**Issue by nazifatanzim** [NicolasDuciaume/SYSC4806_Web_App#7]
This was the first scrum of milestone 1. 
During this meeting, we divided the deliverables into tasks/components.

**Comment by nazifatanzim** [comment]
This was the first scrum of milestone 1. During this meeting we divided the deliverables into tasks/components. I am responsible to developing unit tests. This skeletons of the tests will be created as classes are pushed and updated as functionalities are added.

**Comment by aimansharif** [comment]
For the first scrum of the milestone 1, we divided the tasks into smaller components and assigned ourselves different issues to work on. I am responsible for working on the user controller class and the user repository class for the first milestone.

**Comment by NicolasDuciaume** [comment]
Within this scrum for milestone 1 we have equally separated the tasks amongst all of us. Seeing my previous knowledge over Springboot and form processing I have been set to create the main controller and help with the integration of the form processing within the html files with Christopher
